### PR TITLE
Closes #419, Closes #369, Adds 9.2.5 mounts

### LINKED ISSUE #369: Planner gives impossible advice.
I checked what the mount planner showed for kicks and it's giving impossible advice.

1 | Start off in Orgrimmar | &nbsp; | Make sure you have hearth set to shrine
-- | -- | -- | --
2 | Portal to Orgrimmar | &nbsp; | &nbsp;
3 | Portal to Blasted Lands | &nbsp; | &nbsp;
4 | Fly to Deadwind Pass

Step 3 isn't possible as there is no portal to blasted lands and hasn't been for quite a long time.

### LINKED ISSUE #419: Planner does not show SL
The mount planner does not include SL mounts yet

### PR DESCRIPTION
**Pull request by josh894**
Updates planner for shadowlands mounts, adds new notes for mounts that drop on all 3 difficulties, and removes the portal to Blasted Lands being an option.

### CODE REVIEW

**Comment by seirl** [comment]
Thanks. Is it expected that the planner tells people to hearthstone to different places?

**Comment by josh894** [comment]
Yeah, I tried to base it around the consistency of the steps from whoever added the BFA steps. I was using a fresh planner to test this (My friend's who just started the game @ https://simplearmory.com/#/us/illidan/fatcol/collectable/mounts/planner ) and I saw that at steps 90 and 91 was a double portal to zandalar and assumed that was intended by whoever added the BFA steps.

**Comment by josh894** [comment]
Fixed up some of the consistency of the double portal issues and fixes the notes for multi-run mounts

**Comment by josh894** [comment]
@seirl got a little messy with the commits but I finalized the planner (pre-jailer) and added the two new quest mounts that just came out today (in NA at least)

**Comment by josh894** [comment]
Quickly just wanted to add that I tested that the hawkstrider can be used by any horde character after getting, while the dark iron dwarf mount is exclusive to the race, hence the different parsing of when it should show up on someone's page

**Comment by josh894** [comment]
Yeah, I meant to keep it as a single PR but when I added the new commit on my personal build, I didn't realize it automatically added to any open PR, sorry about that!

**Comment by seirl** [comment]
@josh894 Hey, I'm in vacation so it's hard for me to check, is the planner up to date on the live version? Otherwise I'd like to use your PR when I come back to fix it

**Comment by josh894** [comment]
@seirl yeah, i closed it because I gotta remove the mount stuff i added in order for it to be a clean switch due to the PR that just got pushed. I should push an updated version sometime tomorrow

**Comment by seirl** [comment]
Awesome thanks a lot!

**Comment by josh894** [comment]
@seirl haven't had much time to finally do this, but i'll post my pull request this evening! :D

**Pull request closed without merging**
