### PR TITLE
Added all of the battle pets in Zerith Mortis

### PR DESCRIPTION
**Pull request by aaronincincy**
This commit adds all of the battle pets from Zerith Mortis to the battle pets page.

### CODE REVIEW

**Comment by aaronincincy** [comment]
Fixes #414

**Comment by seirl** [comment]
Hi! All the creature IDs seem wrong, as well as some names. Did you use the dataimporter script? It does all that for you automatically.

https://github.com/kevinclement/SimpleArmory/tree/master/dataimporter

**Comment by seirl** [comment]
Fixed in e51a51ac55859d84425b276a9d3bc7ca130004b5

**Comment by aaronincincy** [comment]
No I was getting errors running the data importer on my machine. I was copying all of the data out of the in-game tooltips from All The Things. I think I was using whatever they call SpeciesId as the CreatureId. Thanks for fixing that.

**Comment by seirl** [comment]
What errors did you encounter? Happy to make changes so that it can be used more easily by potential contributors!

**Comment by aaronincincy** [comment]
I'm guessing it was due to my machine more than your code.  I wasn't able to get the app running locally either without copying all of the contents into a brand new svelte-kit container and running that.  The errors I was getting running SA locally are:

```
Error: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1033:11)
    at defaultResolve (node:internal/modules/esm/resolve:1103:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at load_config (file:///C:/dev/SimpleArmory/node_modules/@sveltejs/kit/src/api/load_config/index.js:63:17)
    at get_config (file:///C:/dev/SimpleArmory/node_modules/@sveltejs/kit/src/cli.js:9:16)
```
That error comes up when I try to run `npm build` or `npm run dev`


When I run the importer I get this (repeating half a dozen times)
```
$ python3 -m dataimporter --fixers pets
INFO:root:Running fixer 'pets'.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000260D7CA31C0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

If I can get these worked out, and be able to contribute better PRs more easily I'd be happy to!  I've been a dev for 15 years but never really contributed much to open source.  This seems like a great place to start.

**Comment by seirl** [comment]
That second one looks to be a Windows-specific error: https://bugs.python.org/issue39232

Could you file a separate issue for it?

**Pull request closed without merging**
