### PR TITLE
Adding header local switch for wowhead tooltip

### PR DESCRIPTION
**Pull request by thelan**
Hello,

I've made a simple patch to add an option on the header for the user to select a wowhead locale for the tooltips and links.
I think this would be a great feature to add on the official page.

### CODE REVIEW

**Comment by Leomelati** [comment]
@thelan You are missing the "Português Brasileiro" option

**Comment by thelan** [comment]
Hello sorry about missing it in the first place. I've added it

**Comment by thelan** [comment]
Hello there,

is there any update on this ? 
Should I change something ?

**Comment by kevinclement** [comment]
I made some changes to the commit.  Namely:
- Moved menu into a profile submenu instead of it being on the main navigation bar
- Smaller submenu items for each locale
- Moved helper function in settings into utils so I could use it in the navigation to determine if already selected

I'm merging with this change, let me know if you have any issues or problems.

**Pull request merged**
