### PR TITLE
Add patch 10.1 updates

### PR DESCRIPTION
**Pull request by tcp13**
Ran data importer for patch 10.1 (this is my first time using the data importer, so please let me know if I did anything incorrectly).

Added and Categorized:
- 126 achievements
- 14 battle pets
- 2 reputations
- 13 mounts
- 49 companions
- 12 titles
- 16 toys

Other Updates:
- marked Season 1 items as unobtainable
- reordered dragon racing achieves (was inconsistent between sub-categories)
- moved dragon racing titles into new sub-category "Dragon Racing" (was getting crowded)
- moved Mossy Mammoth mount from Riddles to new sub-category Zskera Vaults (was miscategorized)
- moved all Dragonflight profession toys to the appropriate Professions section (see conversation on pull request #522 ) and reordered Profession toys sub-categories for better formatting
- confirmed and resolved Issue #523  by moving Kirin Tor Familiar companion from Legion to Wrath category
- confirmed and resolved Issue #524  by moving Toolbox Trouble from Mounts to Pets sub-category and by moving Return to Darkness from Other to Mounts sub-category

### CODE REVIEW

**Comment by seirl** [comment]
Very cool thanks! Why is the diff showing that all lines were changed?

**Comment by tcp13** [comment]
> Why is the diff showing that all lines were changed?

hmm, might be a whitespace issue on my end. Let me look into that...

**Comment by seirl** [comment]
Try to just rerun the dataimporter with --format-only

**Comment by tcp13** [comment]
Revised as #526

**Pull request closed without merging**
