### PR TITLE
[WIP] Dragonflight data import

### PR DESCRIPTION
**Pull request by seirl**
Just keeping this as a draft because I started working on the mounts. There's so little information right now in the wowhead comments that it's really too soon to attempt a categorization.

### CODE REVIEW

**Comment by brikr** [comment]
Hey there!
Would it be reasonable to put all of the mounts into an "Uncategorized" or "Unknown" category so that we can have some UI that shows them? And as we learn where they are from they could be updated.

The way it is now, there are mounts that folks have already collected (e.g. 500 mount achievement or the Dracthyr race mounts) that don't show in the list. The counts are also a little funny because of this

**Comment by seirl** [comment]
Yes, that's usually what I do for the mounts that I can't find. I just paused this because there were just so many of them that were unknown. I will try to have something up before the expansion launch.

**Comment by seirl** [comment]
See #474 which discusses the current issue that stops me from doing the data import for Dragonflight.

**Comment by seirl** [comment]
Merging the mounts for now, we'll open other PRs for the other collectibles.

**Pull request merged**
