### PR TITLE
Updated mount planner with Battle of Dazar'alor mounts

### PR DESCRIPTION
**Pull request by Brian-van-Rheenen**
Added the Battle of Dazar'alor mounts for patch 8.1.0.

### CODE REVIEW

**Comment by seirl** [comment]
I think usually, mounts are only added to the planner when they're from past xpacs, since you can't really just add a whole mythic raid to your "farming route". I might be wrong though?

In any case, if we merge this we need squash that history, there's some commits with weird names.

**Comment by seirl** [comment]
I'm talking about the fact that when you go there: https://github.com/kevinclement/SimpleArmory/pull/149/commits

There's 10 commits instead of a single atomic commit. But it can be taken care of when merging

**Comment by Brian-van-Rheenen** [comment]
I cleaned up the history.
This is the first time I squashed commits. Did I squash them correctly?

**Comment by seirl** [comment]
Yes, but the commit name is wrong: "Updated mount planner with MoP, WoD, Legion and BfA mounts." should say instead something like "mount planner: updated with Battle of Dazar'alor mounts", since that's the only thing your commit does.

**Comment by Brian-van-Rheenen** [comment]
Agreed. I changed the commit name.

**Pull request merged**
