### PR TITLE
add shadowlands factions

### PR DESCRIPTION
**Pull request by slemke**
* added shadowlands factions
* there are "best friends" factions again, but I cannot find a group faction
* but since the profile data does not return the new factions these wont show up anyway

### CODE REVIEW

**Comment by seirl** [comment]
Thanks!

You still have reformatting changes unrelated to your diff. I suggest you run git diff prior to committing to check that each pull request only contains the exact changes you want to send.

I'm kind of surprised by the length of this list. Have you checked that all of these show up in the rep panel? I think it's more likely that most of these are hidden reputations that don't actually register as real reputations, but I might be wrong.

**Comment by slemke** [comment]
Well, yes and no. The thing is, Visual Studio Code respects your [.editorconfig](https://github.com/kevinclement/SimpleArmory/blob/master/.editorconfig) file. Since it says `trim_trailing_whitespace` it trims the whitespace. This is the same issue with the initial json indentation where I added a fix. The python script from the last pull request was actually me, because I reformated stuff to understand whats happening. Unless the `.editorconfig` file gets changed this stuff keeps happening. I only can circumvent this if I somehow disable this or change to an editor without it.

Regarding reputations: most of them are actually part of the bigger factions (like the `Ember Court`). I tried to find a screenshot or something, but even wowhead does not really document this. I can change this PR (or make a new one) by the end of the week, when I find out more ingame.

**Comment by seirl** [comment]
I think we're all fine with reformatting changes to match the editor config. My point is that these should be separate commits, so that the pull request is easier to review.

Re. reputation, maybe for now we could add all the ones mentioned here? https://www.wowhead.com/guides/shadowlands-reputations-overview#shadowlands-faction-overview

**Comment by slemke** [comment]
I disabled the .editorconfig fixes completely, because they happen "on file save" and I can't move them to separate commits/PRs that way. I also added only the reputations from the article. I found a few details about the others: the ember court (not listed in the article, because it is convenant specific) seems to have a lot of npcs with "best friends" rep (see [here](https://www.wowhead.com/news=316864/ember-court-preview-weekly-venthyr-activity-to-throw-a-party)). I also found a list with these reps [here](https://www.wowhead.com/factions/shadowlands/the-ember-court). But with all the changes in the last few weeks, nothing is really confirmed at this point. I backed up the other reps and add them back in a week or so when details are known.

**Comment by seirl** [comment]
Great, thanks!

**Pull request merged**
