### PR TITLE
chore: move some toys and pets from profession tab to dragonflight/profession tab

### PR DESCRIPTION
**Pull request by antony-ramos**
Greetings, 

First thanks for this project, it is awesome ! 

I propose an adjustment about profession toys and pets which are Dragonflight related, but put in Profession Tab. For people like me, it is satisfying to complete all stuff in the current expansion. If it is possible to gather all things related to an expansion inside a single tab it is great in my opinion. 

N.B. : I generate a random id for dragonflight/pets/profession tab and dont know if it is the right way.

### CODE REVIEW

**Comment by tcp13** [comment]
This actually raises a good question - is there a reason Dragonflight is the only expansion with a Professions sub-heading? Perhaps a better way to do this would be to instead move all profession items under the existing Professions heading. That seems more intuitive to me and consistent with past expansions. This also would retain the added benefit of showing which profession produces what.

**Comment by seirl** [comment]
Yes I am confused too. Why not put them in the existing Professions category at the bottom of the page?

**Comment by seirl** [comment]
@tcp13 is this obsolete now?

**Comment by tcp13** [comment]
@seirl Yup - as of #526 all DF profession toys have been moved under the "Professions" heading.

**Comment by seirl** [comment]
Alright, closing this :)
Thank you for your contribution!

**Pull request closed without merging**
