### PR TITLE
Fix mount_fixer.py

### PR DESCRIPTION
**Pull request by slemke**
This PR adds shadowlands mounts from the battle.net API. Here some notes:

* I grouped the mounts by covenants and zone, because most of them have very different sources, which would result in many small categories
* It is not always clear if you need a specific covenant for a mount/rare mob/... which is another reason for the zone grouping
* Some of the wowhead (tooltip) data is incorrect
* I updated the mount fixer, but didn't add the fix to `bnet.py`, because earlier commits use the us api everywhere and I use the eu api. I will add another PR later which moves the region to the `settings.py` and adds the correct mount api endpoint

We probably need to move some mounts once shadowlands launches, because currently the data is incomplete/conflicting/incorrect, but the main work for the mounts is done.

### CODE REVIEW

**Comment by seirl** [comment]
Could you make sure that you're not reindenting the entire file? makes it easier to check what the changes are.

Also, how did you add the item / spell IDs? What database did you use? did you do the join manually or is there a fix missing in the commit?

**Review by seirl — CHANGES_REQUESTED** [review]
As per comment above

**Review by seirl — CHANGES_REQUESTED** [review]
Also, I think grouping by covenant is fine, but the zone grouping is weird. Vendor mounts should go in vendor, rare drops should go in rare, and treasure drops should go in treasures. I don't think you need one category per zone, you should try to be consistent with the grouping done in the previous expansions instead.

**Comment by slemke** [comment]
Sorry for the indentation I didn't notice that. I fixed it and added the changes to the python scripts to give you a full picture of what I did instead of splitting it into another PR. I added the mount data by hand because I could not find a data source for it. Wowhead returns a `403 Forbidden` if you try to scrap their site and wowdb has no way to resolve the ids from the battle.net API (atleast I didn't find one). So there was no automated way to get the data for `icon`, `spellid` and `itemid` .

Here is a full list of the changes:

* added shadowlands mounts
* changed the categories to match the review
* added missing dark iron paladin mounts
* added a new rule to `.editorconfig` so my IDE does not try to indent the json files all the time to 4 spaces
* fixed the mounts fixer
  * added a short description to `bnet.py` and `mounts_fixer.py` functions
  * added support for EU and US endpoints by removing US defaults and adding a `LOCALE` variable to `settings`.
  * introduced a `get_namespace` function because not every endpoint supports the `static` namespace which was hardcoded into the `query` function
  * changed the matching in `mounts_fixer.py` from `itemid` to battle.nets mount id to find missing mounts
  * did some overall refactoring in `bnet.py` to make things more readable
* added an ignore rule to `.gitignore` to ignore intellij/pycharm project files

**Comment by slemke** [comment]
Any news on this @seirl? If this is gets merged I'll take a look at the pets API.

**Comment by seirl** [comment]
I will take a look over this week-end!

**Comment by seirl** [comment]
I'm going to merge some of these commits manually, it would have been easier to split this into different pull requests.

**Comment by seirl** [comment]
A few different things:

- This should really have been multiple PRs. Right now I want to merge the mounts, but the mount fixer requires changes, and I can't easily do a partial acceptance of a single PRs. It would be better if you kept one PR = one change. I also had to manually merge the two commits linked to editorconfig / gitignore.
- You seem to have run a formatting tool on the mount_fixer and the bnet script. Sadly it makes your pull request impossible to review. Could you open a new pull request with your changes to these tools, but without the formatting changes everywhere?
- The mounts still feel inconsistent to me. Dauntless Duskrunner and Gruesome Flayedwing are obtained in the same way but are in two completely different categories (one is in Kyrian and the other in Vendor?). I'm gonna sort this manually, but it would be helpful if you could double check the categories in the future!

Thanks again for the contributions!

**Comment by seirl** [comment]
I merged the mounts with some changes to make it more consistent, so now the only thing remaining in this pull request is the mount_fixer.py that I can't review because of the formatting issues. I had to rename the pull request. It's not an ideal workflow, so I encourage you to split your PRs in the future :-D

**Pull request closed without merging**
