### PR TITLE
Mounts Update

### PR DESCRIPTION
**Pull request by divinemaiden**
The update includes:

1. 8.3 PTR mounts (group id's are missing - not sure what to do here) - made new groups to suit. These are listed as notObtainable for now. These have been added in accordance to wowhead here: https://www.wowhead.com/guides/visions-of-nzoth-content-overview-bfa

2. Sandy Nightsaber moved from Warfronts to Medals (requires 350 Medals in 8.3 PTR) - also listed as notObtainable for now. Link to wowhead: https://www.wowhead.com/news=295582/patch-8-3-build-32151-new-mounts-chalcedony-cloud-serpent-clutch-of-ha-li-sandy-

3. Honeyback Harvester & Pale Thorngazer made Alliance only

4. Both Alabaster mounts added to Shop mounts

### CODE REVIEW

**Comment by seirl** [comment]
Thanks! A few comments:

> group id's are missing - not sure what to do here

Just generate a random alphanumeric ID, e.g:

$ python3 -c "import random; print(''.join(random.choice('0123456789abcdef') for n in range(8)))"
c4872bd6

> Honeyback Harvester & Pale Thorngazer made Alliance only

Are you sure Pale Thorngazer isn't usable on Horde characters? I remember specifically doing this fix because the mounts were usable on the opposite side.

Anyway, there's some weird trailing spaces and indentation issues in your diff, could you reformat it properly?

Thanks.

**Comment by divinemaiden** [comment]
Hi I have no idea what you mean by alphanumeric thing.

Also with the formatting, again I copied an original entry and modified to suit when inserting new entries (did it all via notepad)

As for Pale Thorngazer, you still need an Ally character to acquire the mount as it is purchased separately on an alliance character but yes can be used by a Horde character. So I guess that is open to interpretation with visibility of said mounts which is not too clear. When I think about it, this could stand the same way for the Ankoan ray but definitely not for the Honeyback Harvester where it is an alliance only usable mount.

I thought I'd help out by doing some leg work for you in prep of the next patch but if you don't want to use it, your call :)

**Comment by divinemaiden** [comment]
A new file has been added with spacing issues rectified and restored Ankoan/Unshackled to usable no matter faction as well as Draenor mounts.

**Comment by seirl** [comment]
The diff seems to change the entire file, it's pretty hard to review.

**Comment by seirl** [comment]
Thanks a lot for your contribution, in the end I imported data myself and used what was done by all the different PRs for the new groups. If you find something missing in the current version, don't hesitate to create a new PR, but I think I included everything.

Cheers!

**Pull request closed without merging**
