### PR TITLE
Update dependencies, migration from Snowpack to Vite, some minor fixes

### LINKED ISSUE #358: Migration from Snowpack to Vite?
@kevinclement when I run `npm run dev` I get:

```
SvelteKit now uses https://vitejs.dev. Please remove snowpack.config.js and put Vite config in svelte.config.cjs: https://kit.svelte.dev/docs#configuration-vite
config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
Error: config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
    at Object.validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:188:13)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:518:28)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:516:19)
    at validate_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:587:20)
    at load_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:558:20)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async get_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:616:10)
    at async file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:679:18
```

Any idea how we can migrate this?

### LINKED ISSUE #408: Reputation view bug, one minor overlap
At this link on the website:  https://simplearmory.com/#/us/hyjal/dpartd/reputation

image

Thanks for all you do, your site is amazing overall!  Take care!

### PR DESCRIPTION
**Pull request by maxdekrieger**
__Updated dependencies__ (fixes #358):

* Updated Svelte from `3.23` to `3.47`
* Updated Svelte-kit accordingly (`1.0.0-next.34` to `1.0.0-next.314`)
* Updated Svelte static adapter from `1.0.0-next.2` to `1.0.0-next.29`
* Removed Snowpack, as Svelte-kit now uses Vite under the hood. Transfered the relevant configuration from Snowpack config to Vite config (embedded in Svelte config)

The CLI no longer has `svelte-kit adapt`, the adapt step now always happens when a `svelte-kit build` is executed.

As a bonus, the bumped dependencies make it possible to develop this application on Windows without using a virtual environment.

__Minor changes__:

* Removed some unused/redundant properties and variable declarations to reduce the Svelte warnings.
* Changed CSS for reputation to fix #408

Let me know what you think :)

### CODE REVIEW

**Comment by seirl** [comment]
Thanks, this is awesome. It would be better if @kevinclement reviewed and merged this, I didn't work on this setup at all and I don't really know what I'm looking at. Maybe changing the build system will affect the CD and I have no control over this.

**Comment by maxdekrieger** [comment]
Sounds reasonable, does @kevinclement check this repository every now and again?

**Comment by kevinclement** [comment]
sorry for delay here.  this looks good, thanks for updating to latest.

**Comment by kevinclement** [comment]
doh!  when this deployed in production it was busted.  I'm looking into it, but have to shake off cobwebs since I haven't done this stuff in a while.  It looks like the new svelte doesn't produce an index.html in the build directory like the old one, which is probably why it's busted.

**Comment by kevinclement** [comment]
ok, think I fixed it now :)

**Comment by maxdekrieger** [comment]
No problems at all, thanks for taking the time 👍😄

Shameless plug; I noticed among friends and guildies that SimpleArmory is the go-to tool nowadays for comparing the amount of mounts someone has, that's why I think it would be nice to expose the logic applied in SimpleArmory in an API. (i opened #428 to discuss this)

**Comment by kevinclement** [comment]
thanks for the kind words @maxdekrieger.  I'm glad the tool is providing value.  The fact that it's been a goto has little to do with me recently and everything to do with @seirl and other contributors commitment to keeping the json up to date and curated.  It's a labor of love for them for sure.  I'll go look at other open item and comment there.

**Pull request merged**
