### PR TITLE
Add 10.2.0.52106 mounts

### LINKED ISSUE #558: Missing new mounts from patch 10.2
Hello, we are currently missing the [new mounts from the patch 10.2](https://www.wowhead.com/guide/mounts-patch-10-2):

### PR DESCRIPTION
**Pull request by Ahava**
First PR, hope I sorted everything right! Fixes #558 

- Synced the mount data with the dataimporter script and categorized them into the existing categories to the best of my knowledge. 
- Added two new categories for Dragonflight mounts: 
  - Dreamseeds for mounts that can drop from the  [Emerald Bounty Activity](https://www.wowhead.com/guide/emerald-dream#emerald-bounties-and-emerald-frenzies) or can be bought with [Seedbloom](https://www.wowhead.com/item=211376/seedbloom )
  - Dream Infusion for mounts that can be bought with the [Dream Infusion](https://www.wowhead.com/currency=2777/dream-infusion) currency from [Elianna](https://www.wowhead.com/npc=211209/elianna)

### CODE REVIEW

**Comment by Leomelati** [comment]
@Ahava, Do you mind running all data imports?

**Review by glanzauol — APPROVED** [review]

**Review by psergiopoli — APPROVED** [review]

**Comment by Ahava** [comment]
> @Ahava, Do you mind running all data imports?

I can run the other ones too, though I don't really know battle pets that well to properly categorize them.

**Comment by EagleModdz** [comment]
I checked out this pr, but got this error on the mount page: 


utils.js:46 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toLowerCase')
    at getImageSrc (utils.js:46:72)
    at Object.hydrate [as h] (Mounts.svelte:89:59)
    at Object.create [as c] (Mounts.svelte:76:51)
    at Object.create [as c] (Mounts.svelte:82:23)
    at Object.create [as c] (Mounts.svelte:79:15)
    at Object.create [as c] (Mounts.svelte:73:11)
    at Object.create [as c] (Mounts.svelte:65:12)
    at update2 (index.mjs:1625:19)
    at index.mjs:1641:13

**Comment by thelan** [comment]
After taking a look at the data importer for mounts, it seems that if there no valid icon it outputs a "null" to the json file.
See: https://github.com/kevinclement/SimpleArmory/blob/b324e076e339cea406269ab7508ba77f45245abd/dataimporter/mounts.py#L167-L171

I've made a workaround with a try-catch and forcing a default icon (in a fork) but i think a better solution is to check the presence for the icon at the display side (but i'm not confident with node / svelte.

for reference my fix:
https://github.com/thelan/SimpleArmory/blob/docker/dataimporter/mounts.py#L167-L175

**Comment by drewzybluezy** [comment]
Why has there been little movement on getting this pulled into master? The patch is going into its fourth week with no update so far- is the owner not supporting this anymore?

**Comment by awoodyyc** [comment]
Is this going to go live? 10.2 was released nearly a month ago.

**Comment by kevinclement** [comment]
Sorry, I merged the wrong commit.  You and another dev had similar commits.  If you aren't happy with the results of the merge, let me know or apply the change you want and I can review the PR quickly.

**Pull request merged**
