### PR TITLE
Full migration to modern web framework svelte

### LINKED ISSUE #61: Loading feedback
Feedback: Could you please implement a loading throbber of some sorts

### LINKED ISSUE #102: Feature: Allow deep link to Mount Planner
Kind of hacked this together previously, so it doesn't have a deep link support.

### PR DESCRIPTION
**Pull request by kevinclement**
Test deploy @ https://601bba473b3b730007df24e0--simplearmory.netlify.app/
Branch @ [svelte](https://github.com/kevinclement/SimpleArmory/tree/svelte)

====================

This is a pretty massive change as a fundamental rewrite out of angular into a modern framework.  I'm using [svelte](https://svelte.dev/).  Because I love to live dangerously I am also using a version of svelte-kit that is currently pre-alpha, but still published on npm.  I had to reverse engineer some stuff to make it work because there isn't any docs on it yet.  It will be the most modern way to build svelte apps when it's released, which hopefully is any day now.

I've been testing this pretty heavily over the last week or so, but could use a quick look if anyone is interested.  I actually wrote some automation to screenshot all the pages and did visual diff check against old and new site to make sure there wasn't any regressions.

Below is quick list of things that come with the new version
- [x] full migration to modern framework - svelte
- [x] removed bunch of javascript, jquery, bootstrap, ui-select
- [x] pretty decent perf improvement

| Measurement | Savings  |
| :------------- | :----------: |
|  time to interactive on desktop | 1.8s → .7s   |
| time to interactive on mobile | 7.3s → 2.5s  |
| bundle size | -400kb <br />(24% reduction) |
| load time | -200ms  |
| [lighthouse](https://developers.google.com/web/tools/lighthouse/) score | 89% → 98% |

- [x] added support for app as a PWA, installable from url + in chrome
- [x] added basic offline protection, no caching for now
- [x] added loading indicators to site, resolves #61 
- [x] added ability to deeplink to planner, resolves #102 
- [x] added ability to logout from profile
- [x] added bug reporting to profile dropdown
- [x] added autosave of current character to localstorage and restore it if navigate to root (helps with PWA)
- [x] bunch of accessibility fixes from lighthouse
- [x] fixed some error/login pain points in router
- [x] minor tweaks to title to match current page
- [x] updated favicon and its handling to be proper across browsers
- [x] found two missing toy icons that I fixed the icon path of

### CODE REVIEW

**Comment by kevinclement** [comment]
@seirl Unless I hear otherwise, I'll prob switch a small percentage of traffic over to this version later tonight and watch to see how it goes.  If it looks decent then look to land this PR in the next day or so.

**Comment by seirl** [comment]
Holy cow that's amazing. Do you want us to list issues we encounter here or as separate issues?

A few ones I noticed:

- URL encoding error in the profile: "Signed in as Ana%C3%Bfza @ Archimonde"
- selecting text in the profile modal closes the window
- There seems to be a weird race condition in the realm selection, when I type "arc<tab> really fast it sometimes selects Aegwynn.

I'll definitely do some more testing!

**Comment by kevinclement** [comment]
Awesome.  Just post them here is good.  Great finds already!  I'll have a look at those now.

**Comment by kevinclement** [comment]
@seirl I posted fixes for the first two issues.  However I wasn't able to reproduce that race condition.  I tried different browsers and even tried slowing down CPU and wasn't able to repro.  Is there something special you're doing to repro?

I've published new deploy @ https://601bba473b3b730007df24e0--simplearmory.netlify.app/

**Comment by seirl** [comment]
I'm having a hard time reproducing it, I'll try to see if there's any way I can do it consistently.

Another issue, it looks like "enter" doesn't submit the character selection form?

**Comment by seirl** [comment]
OK, I found how to reproduce the bug. You need to type very quickly:

arc<ENTER><TAB>

If you do it slowly, it selects Archimonde, but if you do it fast enough, it selects Aegwynn every time.

**Comment by kevinclement** [comment]
Perfect, thanks.  I'll give that a try and get a fix in for it if possible.  I'll also fix the enter bug you found.  I'll post back when complete.

**Comment by seirl** [comment]
More info on this, you don't actually need to press everything in quick succession, it's doing `<ENTER><TAB>` quickly that causes the bug!

**Comment by kevinclement** [comment]
Got distracted by life stuff over the weekend.  Just pushed fixes for those issues tonight.

https://deploy-preview-348--simplearmory.netlify.app/#/

I wasn't able to reproduce '<enter> doesn't submit the character selection form'.  There was a bug there, but it was a bug related to not validating.  I fixed that.  However, all times I tried Enter it did submit.  What browser are you using?

**Comment by seirl** [comment]
Both issues seem solved in the latest preview.

**Pull request merged**
