### PR TITLE
Obtainable Feats of Strength - Issue 367

### PR DESCRIPTION
**Pull request by Leomelati**
Adding feature requested in issue #367, feel free to change if any achievement is marked wrong.

### CODE REVIEW

**Comment by Leomelati** [comment]
I don't know if it is a grey area. Does the achievement popup after you get/make something? If it does, it should be marked as obtainable.

Thank you for pointing out the Swift Zulian Tiger and Swift Zandalari Raptor. I forgot that you could still buy it

**Comment by Leomelati** [comment]
Add fix for https://github.com/kevinclement/SimpleArmory/issues/456

**Comment by seirl** [comment]
> Add fix for #456

Hi, can you please make one pull request per change? Some things are easy to merge and others require more discussion, having unrelated changes in the same PR makes everything longer and more confusing.

**Comment by Leomelati** [comment]
Sure @seirl 
Mounts -> https://github.com/kevinclement/SimpleArmory/pull/458
FoS -> https://github.com/kevinclement/SimpleArmory/pull/459

**Pull request closed without merging**
