### PR TITLE
Add many legacy, missing and future titles

### LINKED ISSUE #400: Missing titles
I wrote a script to generate the list of missing titles, then manually removed all the invalid ones. Here are the missing titles:

- Title 28 "High Warlord %s" missing: https://www.wowhead.com/title=28
- Title 63 "%s of the Shattered Sun" missing: https://www.wowhead.com/title=63
- Title 64 "%s, Hand of A'dal" missing: https://www.wowhead.com/title=64
- Title 71 "Vengeful Gladiator %s" missing: https://www.wowhead.com/title=71
- Title 72 "Battlemaster %s" missing: https://www.wowhead.com/title=72
- Title 74 "Elder %s" missing: https://www.wowhead.com/title=74
- Title 75 "Flame Warden %s" missing: https://www.wowhead.com/title=75
- Title 76 "Flame Keeper %s" missing: https://www.wowhead.com/title=76
- Title 77 "%s the Exalted" missing: https://www.wowhead.com/title=77
- Title 79 "%s the Diplomat" missing: https://www.wowhead.com/title=79
- Title 80 "Brutal Gladiator %s" missing: https://www.wowhead.com/title=80
- Title 82 "Arena Master %s" missing: https://www.wowhead.com/title=82
- Title 83 "Salty %s" missing: https://www.wowhead.com/title=83
- Title 84 "Chef %s" missing: https://www.wowhead.com/title=84
- Title 85 "Crashin' Thrashin' %s" missing: https://www.wowhead.com/title=85
- Title 86 "%s of the Ten Storms" missing: https://www.wowhead.com/title=86
- Title 87 "%s of the Emerald Dream" missing: https://www.wowhead.com/title=87
- Title 90 "%s the Malefic" missing: https://www.wowhead.com/title=90
- Title 91 "Predator %s" missing: https://www.wowhead.com/title=91
- Title 96 "Grand Master Alchemist %s" missing: https://www.wowhead.com/title=96
- Title 106 "Grand Master Leatherworker %s" missing: https://www.wowhead.com/title=106
- Title 108 "Grand Master Skinner %s" missing: https://www.wowhead.com/title=108
- Title 109 "Grand Master Tailor %s" missing: https://www.wowhead.com/title=109
- Title 124 "%s the Hallowed" missing: https://www.wowhead.com/title=124
- Title 125 "Loremaster %s" missing: https://www.wowhead.com/title=125
- Title 126 "%s of the Alliance" missing: https://www.wowhead.com/title=126
- Title 127 "%s of the Horde" missing: https://www.wowhead.com/title=127
- Title 128 "%s the Flawless Victor" missing: https://www.wowhead.com/title=128
- Title 132 "%s, Guardian of Cenarius" missing: https://www.wowhead.com/title=132
- Title 134 "Merrymaker %s" missing: https://www.wowhead.com/title=134
- Title 135 "%s the Love Fool" missing: https://www.wowhead.com/title=135
- Title 142 "%s the Undying" missing: https://www.wowhead.com/title=142
- Title 147 "%s of Darnassus" missing: https://www.wowhead.com/title=147
- Title 148 "%s of Ironforge" missing: https://www.wowhead.com/title=148
- Title 154 "%s of the Undercity" missing: https://www.wowhead.com/title=154
- Title 155 "%s the Noble" missing: https://www.wowhead.com/title=155
- Title 156 "Crusader %s" missing: https://www.wowhead.com/title=156
- Title 157 "Deadly Gladiator %s" missing: https://www.wowhead.com/title=157
- Title 158 "%s, Death's Demise" missing: https://www.wowhead.com/title=158
- Title 159 "%s the Celestial Defender" missing: https://www.wowhead.com/title=159
- Title 160 "%s, Conqueror of Ulduar" missing: https://www.wowhead.com/title=160
- Title 161 "%s, Champion of Ulduar" missing: https://www.wowhead.com/title=161
- Title 163 "Vanquisher %s" missing: https://www.wowhead.com/title=163
- Title 164 "Starcaller %s" missing: https://www.wowhead.com/title=164
- Title 165 "%s the Astral Walker" missing: https://www.wowhead.com/title=165
- Title 166 "%s, Herald of the Titans" missing: https://www.wowhead.com/title=166
- Title 167 "Furious Gladiator %s" missing: https://www.wowhead.com/title=167
- Title 168 "%s the Pilgrim" missing: https://www.wowhead.com/title=168
- Title 169 "Relentless Gladiator %s" missing: https://www.wowhead.com/title=169
- Title 170 "Grand Crusader %s" missing: https://www.wowhead.com/title=170
- Title 171 "%s the Argent Defender" missing: https://www.wowhead.com/title=171
- Title 172 "%s the Patient" missing: https://www.wowhead.com/title=172
- Title 173 "%s the Light of Dawn" missing: https://www.wowhead.com/title=173
- Title 174 "%s, Bane of the Fallen King" missing: https://www.wowhead.com/title=174
- Title 175 "%s the Kingslayer" missing: https://www.wowhead.com/title=175
- Title 176 "%s of the Ashen Verdict" missing: https://www.wowhead.com/title=176
- Title 177 "Wrathful Gladiator %s" missing: https://www.wowhead.com/title=177
- Title 191 "Professor %s" missing: https://www.wowhead.com/title=191
- Title 193 "%s, Veteran of the Alliance" missing: https://www.wowhead.com/title=193
- Title 201 "Knight-Lieutenant %s" missing: https://www.wowhead.com/title=201
- Title 208 "Grand Marshal %s" missing: https://www.wowhead.com/title=208
- Title 210 "Grunt %s" missing: https://www.wowhead.com/title=210
- Title 213 "First Sergeant %s" missing: https://www.wowhead.com/title=213
- Title 217 "Centurion %s" missing: https://www.wowhead.com/title=217
- Title 223 "%s, Hero of the Alliance" missing: https://www.wowhead.com/title=223
- Title 224 "%s, Hero of the Horde" missing: https://www.wowhead.com/title=224
- Title 225 "%s, the Bloodthirsty" missing: https://www.wowhead.com/title=225
- Title 226 "%s of the Four Winds" missing: https://www.wowhead.com/title=226
- Title 228 "Dragonslayer %s" missing: https://www.wowhead.com/title=228
- Title 280 "Ruthless Gladiator %s" missing: https://www.wowhead.com/title=280
- Title 281 "Cataclysmic Gladiator %s" missing: https://www.wowhead.com/title=281
- Title 308 "%s the Beloved" missing: https://www.wowhead.com/title=308
- Title 309 "%s the Fearless" missing: https://www.wowhead.com/title=309
- Title 310 "Zookeeper %s" missing: https://www.wowhead.com/title=310
- Title 311 "%s the Relic Hunter" missing: https://www.wowhead.com/title=311
- Title 314 "%s the Undaunted" missing: https://www.wowhead.com/title=314
- Title 315 "%s, Master of the Ways" missing: https://www.wowhead.com/title=315
- Title 316 "%s the Tranquil Master" missing: https://www.wowhead.com/title=316
- Title 333 "Brawler %s" missing: https://www.wowhead.com/title=333
- Title 340 "%s Khan" missing: https://www.wowhead.com/title=340
- Title 349 "Darkspear Revolutionary %s" missing: https://www.wowhead.com/title=349
- Title 350 "Gorgeous %s" missing: https://www.wowhead.com/title=350
- Title 351 "%s the Hordebreaker" missing: https://www.wowhead.com/title=351
- Title 355 "%s the Bloodseeker" missing: https://www.wowhead.com/title=355
- Title 358 "%s the Prime" missing: https://www.wowhead.com/title=358
- Title 359 "%s the Manipulator" missing: https://www.wowhead.com/title=359
- Title 360 "%s the Dissector" missing: https://www.wowhead.com/title=360
- Title 365 "%s the Crazy Cat Lady" missing: https://www.wowhead.com/title=365
- Title 368 "Flameweaver %s" missing: https://www.wowhead.com/title=368
- Title 370 "Darkmaster %s" missing: https://www.wowhead.com/title=370
- Title 371 "Purified Defender %s" missing: https://www.wowhead.com/title=371
- Title 374 "Jade Protector %s" missing: https://www.wowhead.com/title=374
- Title 384 "%s, Hellscream's Downfall" missing: https://www.wowhead.com/title=384
- Title 385 "%s the Proven Assailant" missing: https://www.wowhead.com/title=385
- Title 387 "%s the Proven Healer" missing: https://www.wowhead.com/title=387
- Title 388 "Tyrannical Gladiator %s" missing: https://www.wowhead.com/title=388
- Title 389 "Fire-Watcher %s" missing: https://www.wowhead.com/title=389
- Title 390 "Mistwalker %s" missing: https://www.wowhead.com/title=390
- Title 391 "%s of the Black Harvest" missing: https://www.wowhead.com/title=391
- Title 392 "Lumberjack %s" missing: https://www.wowhead.com/title=392
- Title 393 "Timber Lord %s" missing: https://www.wowhead.com/title=393
- Title 394 "%s the Commandojack" missing: https://www.wowhead.com/title=394
- Title 395 "Architect %s" missing: https://www.wowhead.com/title=395
- Title 397 "Blood Champion %s" missing: https://www.wowhead.com/title=397
- Title 398 "%s the Manslayer" missing: https://www.wowhead.com/title=398
- Title 399 "Gnomebane %s" missing: https://www.wowhead.com/title=399
- Title 400 "%s the Dwarfstalker" missing: https://www.wowhead.com/title=400
- Title 401 "Worgen Hunter %s" missing: https://www.wowhead.com/title=401
- Title 402 "%s, Scourge of the Kaldorei" missing: https://www.wowhead.com/title=402
- Title 406 "%s, Warlord of Draenor" missing: https://www.wowhead.com/title=406
- Title 408 "Orcslayer %s" missing: https://www.wowhead.com/title=408
- Title 409 "%s the Death Stalker" missing: https://www.wowhead.com/title=409
- Title 411 "Troll Hunter %s" missing: https://www.wowhead.com/title=411
- Title 413 "%s, Huojin's Fall" missing: https://www.wowhead.com/title=413
- Title 416 "Talon Queen %s" missing: https://www.wowhead.com/title=416
- Title 418 "%s, Southshore Slayer" missing: https://www.wowhead.com/title=418
- Title 420 "Prelate %s" missing: https://www.wowhead.com/title=420
- Title 421 ""Conservationist" %s" missing: https://www.wowhead.com/title=421
- Title 422 "%s, Spear of Vol'jin" missing: https://www.wowhead.com/title=422
- Title 431 "%s the Soul Preserver" missing: https://www.wowhead.com/title=431
- Title 434 "%s, Lord of Blackrock" missing: https://www.wowhead.com/title=434
- Title 436 "%s the Violet Guardian" missing: https://www.wowhead.com/title=436
- Title 440 "%s, Lord of War" missing: https://www.wowhead.com/title=440
- Title 441 "%s, Lady of War" missing: https://www.wowhead.com/title=441
- Title 442 "%s, Empire's Twilight" missing: https://www.wowhead.com/title=442
- Title 443 "Artisan %s" missing: https://www.wowhead.com/title=443
- Title 444 "%s, Legend of Pandaria" missing: https://www.wowhead.com/title=444
- Title 445 "Field Photographer %s" missing: https://www.wowhead.com/title=445
- Title 446 "Primal Gladiator %s" missing: https://www.wowhead.com/title=446
- Title 448 "%s, Defender of the Alliance" missing: https://www.wowhead.com/title=448
- Title 449 "%s, Soldier of the Alliance" missing: https://www.wowhead.com/title=449
- Title 450 "%s, Guardian of the Horde" missing: https://www.wowhead.com/title=450
- Title 451 "%s, Defender of the Horde" missing: https://www.wowhead.com/title=451
- Title 452 "%s, Soldier of the Horde" missing: https://www.wowhead.com/title=452
- Title 453 "Wild Gladiator %s" missing: https://www.wowhead.com/title=453
- Title 454 "Warmongering Gladiator %s" missing: https://www.wowhead.com/title=454
- Title 455 "Captain %s" missing: https://www.wowhead.com/title=455
- Title 456 "%s of the Jungle" missing: https://www.wowhead.com/title=456
- Title 457 "%s, Defiler's End" missing: https://www.wowhead.com/title=457
- Title 458 "Illidari %s" missing: https://www.wowhead.com/title=458
- Title 462 "Highlord %s" missing: https://www.wowhead.com/title=462
- Title 463 "Slayer %s" missing: https://www.wowhead.com/title=463
- Title 464 "The Honorable %s" missing: https://www.wowhead.com/title=464
- Title 465 "The Prestigious %s" missing: https://www.wowhead.com/title=465
- Title 466 "The Unrelenting %s" missing: https://www.wowhead.com/title=466
- Title 468 "%s, Bound by Honor" missing: https://www.wowhead.com/title=468
- Title 469 "%s, Patron of War" missing: https://www.wowhead.com/title=469
- Title 470 "Archdruid %s" missing: https://www.wowhead.com/title=470
- Title 471 "Deathlord %s" missing: https://www.wowhead.com/title=471
- Title 472 "Grandmaster %s" missing: https://www.wowhead.com/title=472
- Title 473 "Master Assassin %s" missing: https://www.wowhead.com/title=473
- Title 474 "%s, Lord of the Reins" missing: https://www.wowhead.com/title=474
- Title 475 "%s, Guardian of G'Hanir" missing: https://www.wowhead.com/title=475
- Title 476 "%s the Groundbreaker" missing: https://www.wowhead.com/title=476
- Title 477 "%s the Fabulous" missing: https://www.wowhead.com/title=477
- Title 478 "Huntmaster %s" missing: https://www.wowhead.com/title=478
- Title 479 "Farseer %s" missing: https://www.wowhead.com/title=479
- Title 480 "Netherlord %s" missing: https://www.wowhead.com/title=480
- Title 481 "Shadowblade %s" missing: https://www.wowhead.com/title=481
- Title 482 "High Priest %s" missing: https://www.wowhead.com/title=482
- Title 483 "Field Medic %s" missing: https://www.wowhead.com/title=483
- Title 484 "%s the Dreamer" missing: https://www.wowhead.com/title=484
- Title 485 "%s, Vengeance Incarnate" missing: https://www.wowhead.com/title=485
- Title 486 "%s the Gullible" missing: https://www.wowhead.com/title=486
- Title 489 "%s, Talon's Vengeance" missing: https://www.wowhead.com/title=489
- Title 493 "%s the Chosen" missing: https://www.wowhead.com/title=493
- Title 494 "Headmaster %s" missing: https://www.wowhead.com/title=494
- Title 502 "Vindictive Gladiator %s" missing: https://www.wowhead.com/title=502
- Title 503 "%s the Unstoppable Force" missing: https://www.wowhead.com/title=503
- Title 504 "Fearless Gladiator %s" missing: https://www.wowhead.com/title=504
- Title 505 "Stylist %s" missing: https://www.wowhead.com/title=505
- Title 506 "%s the Darkener" missing: https://www.wowhead.com/title=506
- Title 507 "%s, Adventuring Instructor" missing: https://www.wowhead.com/title=507
- Title 508 "Cruel Gladiator %s" missing: https://www.wowhead.com/title=508
- Title 509 "Ferocious Gladiator %s" missing: https://www.wowhead.com/title=509
- Title 510 "Timelord %s" missing: https://www.wowhead.com/title=510
- Title 511 "%s, the Tomb Raider" missing: https://www.wowhead.com/title=511
- Title 512 "Fierce Gladiator %s" missing: https://www.wowhead.com/title=512
- Title 513 "Titanslayer %s" missing: https://www.wowhead.com/title=513
- Title 514 "%s the Collector" missing: https://www.wowhead.com/title=514
- Title 515 "%s, the Lightbringer" missing: https://www.wowhead.com/title=515
- Title 516 "Demonslayer %s" missing: https://www.wowhead.com/title=516
- Title 517 "Dominant Gladiator %s" missing: https://www.wowhead.com/title=517
- Title 518 "%s the Tactician" missing: https://www.wowhead.com/title=518
- Title 519 "Demonic Gladiator %s" missing: https://www.wowhead.com/title=519
- Title 520 "%s, No Good, Dirty, Rotten, Candy Stealer!" missing: https://www.wowhead.com/title=520
- Title 521 "Postmaster %s" missing: https://www.wowhead.com/title=521
- Title 522 "Prospector %s" missing: https://www.wowhead.com/title=522
- Title 524 "%s, Famed Slayer of G'huun" missing: https://www.wowhead.com/title=524
- Title 625 "%s, the Horde Slayer" missing: https://www.wowhead.com/title=625
- Title 626 "%s, the Alliance Slayer" missing: https://www.wowhead.com/title=626
- Title 627 "%s, Conqueror of Azeroth" missing: https://www.wowhead.com/title=627
- Title 628 "Inquisitor %s" missing: https://www.wowhead.com/title=628
- Title 629 "Esteemed %s" missing: https://www.wowhead.com/title=629
- Title 630 "%s the Admired" missing: https://www.wowhead.com/title=630
- Title 631 "%s the Purifier" missing: https://www.wowhead.com/title=631
- Title 632 "Expedition Leader %s" missing: https://www.wowhead.com/title=632
- Title 633 "Contender %s" missing: https://www.wowhead.com/title=633
- Title 634 "%s, Famed Conqueror of Dazar'alor" missing: https://www.wowhead.com/title=634
- Title 635 "%s, Famed Defender of Dazar'alor" missing: https://www.wowhead.com/title=635
- Title 636 "%s, Hero of Dazar'alor" missing: https://www.wowhead.com/title=636
- Title 637 "%s the Elite Death Knight" missing: https://www.wowhead.com/title=637
- Title 638 "%s the Elite Demon Hunter" missing: https://www.wowhead.com/title=638
- Title 639 "%s the Elite Druid" missing: https://www.wowhead.com/title=639
- Title 640 "%s the Elite Hunter" missing: https://www.wowhead.com/title=640
- Title 641 "%s the Elite Mage" missing: https://www.wowhead.com/title=641
- Title 642 "%s the Elite Monk" missing: https://www.wowhead.com/title=642
- Title 643 "%s the Elite Paladin" missing: https://www.wowhead.com/title=643
- Title 644 "%s the Elite Priest" missing: https://www.wowhead.com/title=644
- Title 645 "%s the Elite Rogue" missing: https://www.wowhead.com/title=645
- Title 646 "%s the Elite Shaman" missing: https://www.wowhead.com/title=646
- Title 647 "%s the Elite Warlock" missing: https://www.wowhead.com/title=647
- Title 648 "%s the Elite Warrior" missing: https://www.wowhead.com/title=648
- Title 649 "%s the T-Shirt Enthusiast" missing: https://www.wowhead.com/title=649
- Title 650 "Trashmaster %s" missing: https://www.wowhead.com/title=650
- Title 651 "%s, Famed Slayer of the Harbinger" missing: https://www.wowhead.com/title=651
- Title 654 "Notorious Gladiator %s" missing: https://www.wowhead.com/title=654
- Title 655 "Junkyard %s" missing: https://www.wowhead.com/title=655
- Title 656 "%s the Eternal" missing: https://www.wowhead.com/title=656
- Title 657 "%s of the Deeps" missing: https://www.wowhead.com/title=657
- Title 658 "Sparking %s" missing: https://www.wowhead.com/title=658
- Title 659 "%s, Azeroth's Champion" missing: https://www.wowhead.com/title=659
- Title 660 "Pilgrim %s the Mallet Bearer" missing: https://www.wowhead.com/title=660
- Title 661 "%s, Famed Slayer of Azshara" missing: https://www.wowhead.com/title=661
- Title 662 "Renowned Explorer %s" missing: https://www.wowhead.com/title=662
- Title 664 "%s, Veteran of the Fourth War" missing: https://www.wowhead.com/title=664
- Title 665 "Corrupted Gladiator %s" missing: https://www.wowhead.com/title=665
- Title 666 "%s, As Themselves" missing: https://www.wowhead.com/title=666
- Title 667 "%s, Servant of N'Zoth" missing: https://www.wowhead.com/title=667
- Title 668 "%s, Minion of Mayhem" missing: https://www.wowhead.com/title=668
- Title 669 "%s, Famed Slayer of N'Zoth" missing: https://www.wowhead.com/title=669
- Title 670 "%s the Uncorrupted" missing: https://www.wowhead.com/title=670
- Title 671 "%s the Awakened" missing: https://www.wowhead.com/title=671
- Title 672 "%s the Faceless One" missing: https://www.wowhead.com/title=672
- Title 676 "Cryptkeeper %s" missing: https://www.wowhead.com/title=676
- Title 678 "%s, Hand of the Archon" missing: https://www.wowhead.com/title=678
- Title 679 "Baron %s" missing: https://www.wowhead.com/title=679
- Title 680 "Baroness %s" missing: https://www.wowhead.com/title=680
- Title 681 "%s, Winter's Envoy" missing: https://www.wowhead.com/title=681
- Title 682 "Count %s" missing: https://www.wowhead.com/title=682
- Title 683 "Countess %s" missing: https://www.wowhead.com/title=683
- Title 684 "Deathbringer %s" missing: https://www.wowhead.com/title=684
- Title 685 "%s the Proud" missing: https://www.wowhead.com/title=685
- Title 686 "Sinbreaker %s" missing: https://www.wowhead.com/title=686
- Title 687 "%s, the Party Herald" missing: https://www.wowhead.com/title=687
- Title 688 "Sinful Gladiator %s" missing: https://www.wowhead.com/title=688
- Title 689 "Fun Guy %s" missing: https://www.wowhead.com/title=689
- Title 690 "%s the Avowed" missing: https://www.wowhead.com/title=690
- Title 691 "Abominable %s" missing: https://www.wowhead.com/title=691
- Title 692 "Spirestalker %s" missing: https://www.wowhead.com/title=692
- Title 693 "%s the Ascended" missing: https://www.wowhead.com/title=693
- Title 694 "%s, Famed Slayer of Denathrius" missing: https://www.wowhead.com/title=694
- Title 698 "Unchained Gladiator %s" missing: https://www.wowhead.com/title=698
- Title 699 "%s, Protector of the Weald" missing: https://www.wowhead.com/title=699
- Title 700 "%s, Sword of the Primus" missing: https://www.wowhead.com/title=700
- Title 701 "Sin Eater %s" missing: https://www.wowhead.com/title=701
- Title 702 "%s, Disciple of Devotion" missing: https://www.wowhead.com/title=702
- Title 703 "%s the Tormented" missing: https://www.wowhead.com/title=703
- Title 704 "%s, Breaker of Chains" missing: https://www.wowhead.com/title=704
- Title 705 "%s, Famed Bane of the Banshee Queen" missing: https://www.wowhead.com/title=705

@finnlux do you want to take a shot at it?

### PR DESCRIPTION
**Pull request by maxdekrieger**
fixes #400 and #430, let me know what you think.

# Contributions

This PR contains two contributions:

* **Categorize titles from titlesfixer.**
    * This PR introduces a new category "Legacy" for titles that are no longer obtainable with many fitting subcategories. I chose for a new category to get a clear overview of what awesome legacy titles one has, instead of silently adding them to existing categories.
    * Some obtainable titles in exsting categories.
    * A new subcategory for arena titles (Challenger, Rival, Duelist, etc.) with an indication that they are temporary and are lost after a season ends.
    * Some future titles for Shadowlands season 3 and 9.2.5 are added already, but with a `notObtainable` property so they are not shown yet.
* **Add support for hidable category headers in the titles api.**
    * This was necessary to make it look good when a character does not have any unobtainable titles, it would just show a loose category header
    * A category is not shown when both conditions are met: 
        1. The category has the `notObtainable` property (with a true value)
        2. The category does not have any visible subcategories

# Screenshots

## New Legacy category

legacy-title-category

### CODE REVIEW

**Comment by maxdekrieger** [comment]
According to Netlify it's missing some kind of access token in an environment variable. Is this something I can assist with?

**Comment by maxdekrieger** [comment]
Update: set Deathbringer title to unobtainable after a good catch of @TheKrowi in #430.

**Comment by seirl** [comment]
I think all the temporary titles should be removed and added to a blacklist in the fixer. They are not really "collectibles".

**Comment by maxdekrieger** [comment]
Right, that makes sense 👍 Tomorrow I'll merge the titles fixer branch into my local master, and include that in this PR, or is there a reason that it's a separate branch?

**Comment by seirl** [comment]
Yes, it's in a separate branch because I want the fixers on the master branch to not do anything if there are nothing new to add. So I wanted all the titles to be there first before merging it.

**Comment by maxdekrieger** [comment]
The branch now includes the titlefixer script, and an updated blacklist that includes many temporary titles and titles that were never obtainable in the game.

The result of running the titlesfixer is still two uncategorized titles, but they seem to be placeholder titles...

titlefixer-result

**Comment by maxdekrieger** [comment]
@seirl @kevinclement I'm sorry for continuing to tag you in stuff like this 😅. Are there any days/hours you usually look at these kind of things? Then I hope I can keep my childlike impatience in check.

**Comment by kevinclement** [comment]
This stuff looks all good to me, but I'm gonna let @seirl have the final say here and control the PR since he's a lot closer to this stuff as is.  I need to look into that netlify stuff, it's confused.  I didn't realize I had this hooked up so I need to go make it intention and make sure it works properly for PRs.

**Comment by seirl** [comment]
Huh, I accidentally closed this by pushing the wrong thing, and now I no longer have the permission to push to your branch because the PR is closed. I'll have to open a new PR.

**Pull request closed without merging**
