### PR TITLE
[Added] 10.2 & 10.2.5 Items

### PR DESCRIPTION
**Pull request by EagleModdz**
All items found by the data importer on 20.11 have been added.

### CODE REVIEW

**Comment by josh894** [comment]
This looks great! 

As a mount collector, I do prefer the sorting of the mounts in #559 

I think it adds clarity for users who are trying to go to past expansions trying to collect mounts, separating the Dream Infusion mounts from the vendor tab into their own section.

Along with Ochre Dreamtalon being added to the daily activity tab due to it's 25 day questline. :)

**Comment by F0ri0n** [comment]
Thanks a lot for your work on this! Looks really good! Few minor things I have noticed.

I wish I could fix them myself but I unfortunately have no clue about coding. Just wanted to point them out. Hope it helps.

----

The "Of the Tyr's Guard" achievement is missing under Dragonflight -> Quests

https://www.wowhead.com/achievement=18958/of-the-tyrs-guard

----

The Feats of Strength "Dragonflight Season 3 Master" and "Dragonflight Season 3 Hero" are listed under 
FoS -> Dungeons -> Mythic Keystone: Dragonflight while the Season 2 achievements are listed under FoS -> Other

As they are not exclusively related to M+ I would recommend adding them to FoS -> Other

- https://www.wowhead.com/achievement=19396/dragonflight-season-3-master
- https://www.wowhead.com/achievement=19420/dragonflight-season-3-hero

----

Same goes for the Feats of Strength "Dreaming of Drakes", "Dreaming of Wyrms", "Dreaming of the Aspects" 

- https://www.wowhead.com/achievement=19326/dreaming-of-drakes
- https://www.wowhead.com/achievement=19397/dreaming-of-wyrms
- https://www.wowhead.com/achievement=19398/dreaming-of-the-aspects

----

The mount "Armored Siege Kodo" is still listed under Mounts -> Unknown. The source is the Blizzard Store so it should be added to Promotion -> Blizzard Store 

- https://www.wowhead.com/item=190636/armored-siege-kodo

----

The Season 2 Gladiator Mount "Obsidian Gladiator's Slitherdrake" is still marked as obtainable.

- https://www.wowhead.com/item=205233/obsidian-gladiators-slitherdrake

----

The mount "Bound Blizzard" is currently listed under Mounts -> Promotions -> Anniversairies.
The correct source however is from the Blizzcon virtual Goodie Bag. So it should be listed under Mounts -> Promotions -> Blizzcon

- https://www.wowhead.com/spell=358072/bound-blizzard

----

While Superbloom mounts have their own subcategory, pets currently do not and are listed under "Vendor". I would recommend adding a "Suberbloom" subcategory for the pets aswell for consistency.

- https://www.wowhead.com/npc=212328/napps
- https://www.wowhead.com/npc=212329/snoozles
- https://www.wowhead.com/npc=212408/seedle
- https://www.wowhead.com/npc=212413/dustite
- https://www.wowhead.com/npc=212562/snoots
- https://www.wowhead.com/npc=212567/elmer

----

The pet "Crushhoof" is currently listed under Companions -> Promotions -> Trading Post.
The correct source is however the Blizzard store so it should be listed under Companions -> Promotions -> Blizzard Store

- https://www.wowhead.com/npc=185611/crushhoof

----

The pets "Crimson Swoglet" and "Cheddar" are still listed under "Unknown". Their source is the Dreamsurge vendor so I would recommend adding them to Companions -> Dragonflight -> Vendor

- https://www.wowhead.com/npc=204226/crimson-swoglet
- https://www.wowhead.com/npc=204268/cheddar

----

The pet "Rithro" is also still listed under "Uknown" when it is in fact a quest reward from the Emerald Dream". I would recommend adding it to Companions -> Dragonflight -> Quest

- https://www.wowhead.com/item=205160/rithro

----

The pet "Mister Muskoxeles" is still listed as obtainable under Companions -> Collect

This pet was however removed and is currently not obtainbale

- https://www.wowhead.com/npc=188901/mister-muskoxeles

----

The pets "Bestial Lurker", "Snapjaw Lurker" and "Void Lurker" are currently listed under Companions -> Professions -> Fishing.

These pets are however currently unobtainable and their source is unknown.

- https://www.wowhead.com/npc=204271/bestial-lurker
- https://www.wowhead.com/npc=204275/snapjaw-lurker
- https://www.wowhead.com/npc=204276/void-lurker

----

The toy "Verdant Legend's Pennant" is currently listed under Toys - > Promotions -> WoW Esports while the one from Season 2 is listed under Toys -> PVP -> Solo Shuffle. I would recommend adding the Season 3 one there aswell.

- https://www.wowhead.com/item=210497/verdant-legends-pennant

---- 

The toy "Dreaming Banner of the Aspects"  is currently listed under Toys - > Promotions -> WoW Esports while the ones from Season 1 and 2 are listed under Toys -> Dragonflight -> Mythic Dungeon Invitational. I would recommend adding the Season 3 one there aswell.

- https://www.wowhead.com/item=211424/dreaming-banner-of-the-aspects

**Comment by mmofanatic90210** [comment]
> Thanks a lot for your work on this! Looks really good! Few minor things I have noticed.
> 
> I wish I could fix them myself but I unfortunately have no clue about coding. Just wanted to point them out. Hope it helps.
> 
> The "Of the Tyr's Guard" achievement is missing under Dragonflight -> Quests
> 
> * https://www.wowhead.com/achievement=18958/of-the-tyrs-guard
> 
> The Feats of Strength "Dragonflight Season 3 Master" and "Dragonflight Season 3 Hero" are listed under FoS -> Dungeons -> Mythic Keystone: Dragonflight while the Season 2 achievements are listed under FoS -> Other
> 
> As they are not exclusively related to M+ I would recommend adding them to FoS -> Other
> 
> * https://www.wowhead.com/achievement=19396/dragonflight-season-3-master
> * https://www.wowhead.com/achievement=19420/dragonflight-season-3-hero
> 
> Same goes for the Feats of Strength "Dreaming of Drakes", "Dreaming of Wyrms", "Dreaming of the Aspects"
> 
> * https://www.wowhead.com/achievement=19326/dreaming-of-drakes
> * https://www.wowhead.com/achievement=19397/dreaming-of-wyrms
> * https://www.wowhead.com/achievement=19398/dreaming-of-the-aspects
> 
> The mount "Armored Siege Kodo" is still listed under Mounts -> Unknown. The source is the Blizzard Store so it should be added to Promotion -> Blizzard Store
> 
> * https://www.wowhead.com/item=190636/armored-siege-kodo
> 
> The achievements for collecting Flightstones are still listed under Exploration -> Dragon Isles -> Zaralek Cavern. As they are not specifically related to Zaralek Cavern, I would recommend creating a new subcategory Exploration -> Dragon Isles -> Flightstones
> 
> * https://www.wowhead.com/achievement=17830/stones-cant-fly
> * https://www.wowhead.com/achievement=17977/stones-can-try-to-fly
> * https://www.wowhead.com/achievement=17978/stones-can-fly
> 
> The Season 2 Gladiator Mount "Obsidian Gladiator's Slitherdrake" is still marked as obtainable.
> 
> * https://www.wowhead.com/item=205233/obsidian-gladiators-slitherdrake
> 
> The mount "Bound Blizzard" is currently listed under Mounts -> Promotions -> Anniversaries. The correct source however is from the Blizzcon virtual goodie bag. So it should be listed under Mounts -> Promotions -> Blizzcon
> 
> * https://www.wowhead.com/spell=358072/bound-blizzard
> 
> While Superbloom mounts have their own subcategory, pets currently do not and are listed under Companions -> Dragonflight -> Vendor. I would recommend adding a subcategory for the pets aswell for consistency. And I would suggest calling it "Emerald Bounty" for both pets and mounts as they are not from the Superbloom.
> 
> * https://www.wowhead.com/npc=212328/napps
> * https://www.wowhead.com/npc=212329/snoozles
> * https://www.wowhead.com/npc=212408/seedle
> * https://www.wowhead.com/npc=212413/dustite
> * https://www.wowhead.com/npc=212562/snoots
> * https://www.wowhead.com/npc=212567/elmer
> 
> The pet "Crushhoof" is currently listed under Companions -> Promotions -> Trading Post. The correct source is however the Blizzard store so it should be listed under Companions -> Promotions -> Blizzard Store
> 
> * https://www.wowhead.com/npc=185611/crushhoof
> 
> The pets "Crimson Swoglet" and "Cheddar" are still listed under Companions -> Dragonflight -> Unknown. Their source is the Dreamsurge vendor so I would recommend adding them to Companions -> Dragonflight -> Vendor
> 
> * https://www.wowhead.com/npc=204226/crimson-swoglet
> * https://www.wowhead.com/npc=204268/cheddar
> 
> The pet "Rithro" is also still listed under Companions -> Dragonflight -> Unknown when it is in fact a quest reward from the Emerald Dream. I would recommend adding it to Companions -> Dragonflight -> Quest
> 
> * https://www.wowhead.com/item=205160/rithro
> 
> The pet "Mister Muskoxeles" is still listed as obtainable under Companions -> Collect
> 
> This pet was however removed and is currently not obtainbale
> 
> * https://www.wowhead.com/npc=188901/mister-muskoxeles
> 
> The pets "Bestial Lurker", "Snapjaw Lurker" and "Void Lurker" are currently listed under Companions -> Professions -> Fishing.
> 
> These pets are however currently unobtainable and their source is unknown.
> 
> * https://www.wowhead.com/npc=204271/bestial-lurker
> * https://www.wowhead.com/npc=204275/snapjaw-lurker
> * https://www.wowhead.com/npc=204276/void-lurker
> 
> The toy "Verdant Legend's Pennant" is currently listed under Toys - > Promotions -> WoW Esports while the one from Season 2 is listed under Toys -> PVP -> Solo Shuffle. I would recommend adding the Season 3 one there aswell.
> 
> * https://www.wowhead.com/item=210497/verdant-legends-pennant
> 
> The toy "Dreaming Banner of the Aspects" is currently listed under Toys - > Promotions -> WoW Esports while the ones from Season 1 and 2 are listed under Toys -> Dragonflight -> Mythic Dungeon Invitational. I would recommend adding the Season 3 one there aswell.
> 
> * https://www.wowhead.com/item=211424/dreaming-banner-of-the-aspects


To add, and I would be more than happy to reorganize what I could within the existing .json's if it was as simple as text editing within existing brackets... (the header ID's I am unfamiliar with, but within existing, seems straightfoward). If there's documentation on how to aid in this, I absolutely would. Data importing/etc, not so much but organizational, icon Ids from wowhead/etc, naming - 100%. Simplearmory is hugely popular with collectors and I wish the owners/caretakers that aren't recognized enough, would be. This site is amazing. Truly. A part of me thinks Blizz should adopt this site. They very well know its value (their site is useless for 'stamping' missing slots)

Anyway!

This toy is listed as a Raid toy, but is in fact off a Rare (move here in SA) in Emerald Dream overland zone, not raid/etc.

          {
            "ID": 1321,
            "icon": "spell_burningbladeshaman_molten_torrent",
            "itemId": 205463,
            "name": "Molten Lava Ball"
          },

**Comment by EagleModdz** [comment]
Thank you very much for your feedback! I will implement your feedback over the following days. In the case, that the contributors do not maintain this repository, I will temporarily deploy this site, on my web server, that means you can use my version under a different domain. For the contributors, if you don't agree with it, please contact me, then I will take the site offline.

**Comment by seirl** [comment]
It is maintained, we just have real life stuff and cannot always work on the website just after a release.

Thanks for the work! There are now two pull requests that import the same data though. If you do the fixes that have been suggested to you, I think I'll start from yours and then look at the ordering differences for mounts.

**Comment by EagleModdz** [comment]
I have implemented the feedback, I hope it all fits :D 
Thanks again to everyone who sent feedback!

**Comment by F0ri0n** [comment]
@EagleModdz this looks excellent! Thanks so much for your work on this!

**Comment by SolestialDev** [comment]
I noticed the order of the Amirdrassil achievements is a little off in comparison to the other raids.

In this version the order is:
6 raid achievements --> full completion normal/heroic/mythic --> mythic boss achievements --> wing achievements --> 3 raid achievements
The expected order is:
wing achievements --> full completion normal/heroic/mythic --> mythic boss achievements --> all raid achievements

Could you adjust this, just to keep it consistent?

**Comment by EagleModdz** [comment]
@SolestialDev Thank you for your feedback, I have just changed both. Yes, I had unfortunately overlooked the ochre dreamtalon topic, sorry.

**Pull request merged**
