### PR TITLE
Add Dragonflight titles

### PR DESCRIPTION
**Pull request by Leomelati**

### CODE REVIEW

**Comment by seirl** [comment]
Awesome. Is there a diff with the fixer output? Surprised that you didn't have to add anything to the blacklist.

**Comment by maxdekrieger** [comment]
Nice PR!

About the unknown section: Honorary Dryad and Worldbreaker are not really unknown but they are temporary. The first one is obtained for one hour after completing a one-time quest, and is required to collect a pet (horrible design, i know). The second one is also temporary from buying a worldbreaker contract in the obisidian citadel. Also, maybe it's good to add `notObtainble: true` to the the last title in the unknown section.

**Comment by maxdekrieger** [comment]
Another point: not sure what the standard is here; but the Hall of Fame for this season will close at some point so it's probably okay to add notObtainable or already move it to the legacy section with the notObtainable? But I don't know what the standard procedure is here (@seirl )

**Comment by Leomelati** [comment]
About @seirl's question, I don't have any log file from the fixer, I don't know if I did something wrong, but I have this print from the console:

- Title 467 "Honorary Dryad" missing: https://www.wowhead.com/title=728
- Title 468 "Crimson Gladiator" missing: https://www.wowhead.com/title=15951
- Title 469 "The Worldbreaker" missing: https://www.wowhead.com/title=13931
- Title 470 "The Thundering Hero" missing: https://www.wowhead.com/title=16429
- Title 471 "Soupervisor" missing: https://www.wowhead.com/title=16443
- Title 472 "Birdwatcher" missing: https://www.wowhead.com/title=16446
- Title 473 "Khansguard" missing: https://www.wowhead.com/title=734
- Title 474 "Ally of Dragons" missing: https://www.wowhead.com/title=735
- Title 475 "Intrepid Explorer" missing: https://www.wowhead.com/title=736
- Title 476 "Of Iskaara" missing: https://www.wowhead.com/title=737
- Title 477 "The Thundering" missing: https://www.wowhead.com/title=16648
- Title 478 "Isles Racer" missing: https://www.wowhead.com/title=15941
- Title 479 "Malicious" missing: https://www.wowhead.com/title=16601
- Title 480 "Knight of Feathersworth" missing: https://www.wowhead.com/title=16731
- Title 481 "The Elite Evoker" missing: https://www.wowhead.com/title=742
- Title 482 "Crimson Soloist" missing: https://www.wowhead.com/title=16734
- Title 483 "Paragon of the Obsidian Brood" missing: https://www.wowhead.com/title=16760
- Title 484 "Agent of the Black Prince" missing: https://www.wowhead.com/title=16494
- Title 485 "Merchant Artisan" missing: https://www.wowhead.com/title=16791
- Title 486 "Personal Crafter" missing: https://www.wowhead.com/title=16799
- Title 487 "Famed Slayer of Raszageth" missing: https://www.wowhead.com/title=17116
- Title 488 "The Storm-Eater" missing: https://www.wowhead.com/title=16353

Regarding @maxdekrieger's comments, I had seen that these titles were temporary but didn't know if there was another one with the same behavior, so I left them as `notObtainable`. I believe it makes sense to add them to the data import blacklist and mark the other title in the "Unknown" section as `notObtainable` until we have more information.

I don't know the default for the titles but I remember on the mounts we were leaving them with the `notObtainable` flag false and when the season was over, we changed it to true. It might be interesting to define a rule for both titles and mounts.

**Comment by seirl** [comment]
Thanks!

**Pull request merged**
