### PR TITLE
Add dragonflight toys

### PR DESCRIPTION
**Pull request by Leomelati**
Added Dragonflight missing toys as pointed out at #487

### CODE REVIEW

**Review by falt86 — APPROVED** [review]

**Comment by maxdekrieger** [comment]
would be awesome if we could merge this @seirl

**Comment by maxdekrieger** [comment]
I was checking if this was up-to-date with the latest dataimport (`python -m dataimporter --build 10.0.2.47213 --fixers toys`) but appearantly the Tuskarr Training Dummy is (temporarily) removed because of a bug: https://www.wowhead.com/item=199830/tuskarr-training-dummy#comments.

If you could remove that toy, this PR is completely up-to-date with the latest data import. (@seirl @Leomelati )

**Comment by Leomelati** [comment]
@maxdekrieger fixed

**Comment by seirl** [comment]
Thanks!

**Pull request merged**
