### PR TITLE
Add 10.1.5 data from DB2 files

### PR DESCRIPTION
**Pull request by maxdekrieger**
This PR contains all 10.1.5 data from my locally exported db2 and hotfix files: https://github.com/maxdekrieger/wow-csv-from-db2s/

Except for the mounts added previously of course :) 

Work in progress.

### CODE REVIEW

**Comment by josh894** [comment]
Yo! 

I know i just added the mounts earlier but of course Blizzard had to add a store mount while i'm gone for the weekend 😭

https://twitter.com/wowhead/status/1679919538563842064?s=46&t=ZqyNBLTEfDHgGgIlp0C7YA

I don't think I'll be making a separate PR just to add it so if you could add it to yours that would be great!


Also, i was wondering if you're having issues locally with the new icons for some of the mounts that the dataimporter automatically changed, they weren't working for me when i was developing.

**Comment by maxdekrieger** [comment]
@josh894 I saw your PR, thanks a lot.

Regarding new mounts and messed up icons, if you used the regular data importer it gets its info from wago.tools which does not include hotfix data. My repo in the description of this PR is just a local export using wow.export and it includes hotfix data, which sometimes contains new mounts/achievements/fixed icons 😄

**Comment by maxdekrieger** [comment]
Fixes #545

**Comment by maxdekrieger** [comment]
@seirl 👀

**Comment by seirl** [comment]
\o/

**Pull request merged**
