### PR TITLE
Added fated raids achievements and mount

### PR DESCRIPTION
**Pull request by saah13**
**Changes:**

- Added Fated achievements from the 9.2.5 patch
- Added mount and title reward from the 9.2.5 patch

### CODE REVIEW

**Comment by maxdekrieger** [comment]
Perfect, it includes all new additions from season 4.
Looks good to me.

**Comment by maxdekrieger** [comment]
@kevinclement @seirl The new season with these new additions has been out for ~10 days now 😄

**Comment by seirl** [comment]
Thanks. Unfortunately these changes were made manually instead of using dataimporter, so I see some data discrepancies that make this more complex than a simple accept & merge. I'll try to merge them soon but I'm in vacation with unreliable internet.

**Comment by seirl** [comment]
Obsoleted by 6b113f8e341f1c2f51fc81da4d51ca4f371fdc78 which partially includes your ordering. Thanks for the PR! Don't hesitate to check out https://github.com/kevinclement/SimpleArmory/tree/master/dataimporter next time.

**Pull request closed without merging**
