### PR TITLE
Mounts: Glad/Brawler fix

### PR DESCRIPTION
**Pull request by josh894**
Same commit but with a new clean fork

### CODE REVIEW

**Comment by josh894** [comment]
Now i'm confused lol, any idea on what is causing checks to fail?

**Comment by seirl** [comment]
It's got nothing to do with you, it's a general problem that @kevinclement is investigating.

**Comment by kevinclement** [comment]
ok.  fixed it.  It will not do checks proper, and also do a deploy preview with pull requests so you can check if sight is busted.

**Comment by josh894** [comment]
perfect! I also had a question about the id system for each different section for the mount tab on the website. I was just wondering how those ids are derived and if their values have any meaning, or could I go in to the json and create a new tab for Torghast under Shadowlands for my issue #436

**Comment by kevinclement** [comment]
Those ids are just random generated to have uniqueness to help with tooling.

**Pull request merged**
